# See the documentation for more information:
# https://github.com/packit-service/packit/blob/master/docs/configuration.md


specfile_path: 5minute.spec
upstream_package_name: 5minute
downstream_package_name: 5minute
upstream_project_url: https://github.com/ogajduse/5minute

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable
