language: python
python:
- '3.6'
sudo: required
before_install:
  - "sudo apt-get install pandoc"
  - "pandoc --from=markdown --to=rst --output=README README.md"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install pycodestyle"
script:
  - pycodestyle
deploy:
- provider: pypi
  skip_cleanup: true
  distributions: "sdist"
  user: ogajduse
  password:
    secure: "pDH+jHI4JKpA7JmISfmiL0oT7AFVp5qRafPERr30MgO2Aj8S8mdoUQ1uHR7owDxKERpkhi6Lq+ybITvqqtH3m3UJrCfeZPqxtFhDNnVdKOjZgybHkjCHEPRaeILW4N9gI6JuuxqF0w0SdIzajrAdFU4Sdl9rF1oi4rLMedyPWPJleWnbhpe7zMIq6Ahk8Ivoz6pJxgDJfH5ti0mYHGACOJbJFMsLgHyVg23Npmep8W42iqQ62x9n1CdBB+j/COJT0O2PURm/uV3GF8Hq41ZoOYqHKl5bI2QFNmn1AM3vP6lg8x3thyh5SZ7WM2C2cGquIOIyVDX9ggGa2uUiHh6IWnVScJKLUbfYYCCOl06LR8EXsq00NeD5SbvY+iak4AX64pdwEwYapX11d+3T/FPX+n/WVNrYUu8Ilft43+8NsVv2ZAkStDva080X5b/gTOJK4A5qsvranCAlw1OtnaZZc123Cs1S2hgIjvIlY01uNUxBwy3gZ9Ph9x9bIcj7YNFDIaovYwioBuPKM3r+LleXX8eYgwMoiZwWzICkbLG3YQBs+AMM92Q18UOGf8Cck5MpYdtgiar1emagKocQgRMR4Qv3hnNNR4pZGj3tSKdT4rxIJHl1y2On6c7FrRHiFcvzhehJYwUndbfB1VgvV41mSzljPcoL+2GHFHQq1iYYt7Y="
  on:
    tags: true
    all_branches: true
#    condition: $TRAVIS_PYTHON_VERSION = 3.6
#    branch: master    
